### ISSUE TITLE
Cloning: Permission Denied

### ISSUE THREAD

**Issue by calebgrove** [mauricerenck/kirby-podcast#1]
When I run `git submodule add git@github.com/mauricerenck/kirby-podcast.git podcast`, I got this error:

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:mauricerenck/kirby-podcast.git' into submodule path 'site/plugins/podcast' failed
```

This can be solved by using the HTTP URL (`http://github.com/mauricerenck/kirby-podcast.git`) instead of the SSL URL (`git@github.com:mauricerenck/kirby-podcast.git`). Source: http://stackoverflow.com/a/16465182/2521683

**Comment by mauricerenck** [comment]
Thank you for the hint!
I updated the Readme and Plugin-Info and changed the urls to the https://
