### ISSUE TITLE
Kirby CLI integration

### ISSUE THREAD

**Issue by voidit** [mauricerenck/kirby-podcast#2]
Hello,
I'm getting an error when trying to install via Kirby CLI
```
kirby plugin:install kirby-podcast

[RuntimeException]                       
  The source directory could not be found 
```

It's not an "issue", but it would be nice to have :)

Thanks!
Irena.

**Comment by mauricerenck** [comment]
Hey Irena,

thank you for you feedback.

I am currently working on a new major version, which will come with an updated structure and the ability to be installed via the Kirby CLI.

I hope, I can publish this new version within the next weeks.

Greetings,
Maurice

**Comment by mauricerenck** [comment]
I am happy to announce Version 2 of this plugin, which now support Kirby CLI :)
